### PR TITLE
Minimal working example of `safetensors` support for `hezar`

### LINKED ISSUE #153: Weight conversion to `safetensors` format
In the wake of security concerns associated with the `pickle` module (see [this](https://github.com/pytorch/pytorch/issues/52596)), almost all of the new entries at HF are in the new `safetensors` format which seems to be becoming the de facto replacement for `pickle` at this rate (see [this](https://huggingface.co/CohereForAI/c4ai-command-r-plus/tree/main) by Cohere for instance). Not only has it been shown that unlike `pickle`, arbitrary code execution is impossible through `safetensors`, `safetensors` also reduces potential RAM usage for bigger models through sharding and it demonstrates a loading speed-up of up to [2x on GPU and up to 76.6x on CPU](https://huggingface.co/docs/safetensors/speed).

I would like to propose a simple solution that allows you to serve your trained models on HF using the new `safetensors` format. The official `safetensors` HF page has a [space](https://huggingface.co/spaces/safetensors/convert) that allows for very simple conversion of already existing models. This page, although very streamlined, has the drawback that existing model weights need to follow a certain naming convention (`pytorch_model.bin` or `pytorch_model-xxxx-of-xxxx.bin`). 

Moreover, for offline conversion and a more customizable approach, I can refer you to [a script from the text-generation-webui repository](https://github.com/oobabooga/text-generation-webui/blob/main/convert-to-safetensors.py) which is an actively maintained repository, and [this](https://github.com/Silver267/pytorch-to-safetensor-converter/blob/main/convert_to_safetensor.py).

I understand that this may not be a priority at this time and I can potentially volunteer a PR myself later when I find some free time if this pitch sounds reasonable to you.

I'd like to close this out by thanking you for your tremendous work on advancing Persian NLP and saving countless hours of research time.

### PR DESCRIPTION
**Pull request by Adversarian**
# Pull Request

## Description
The `save` and `load` methods for the `hezar.models.Model` class have been altered to accommodate for `safetensors` support.  

## Changes

- Loading `safetensors` exposed through the keyword argument `load_safetensors` under `Model.load()`.
- Saving `safetensors` exposed through the keyword argument `safe_serialization` under `Model.save()`.
- `SAFETENSORS` added to the `enumlist` of `Backends` in `constants.py`.
- A minimal working example unittest is available at `test_safetensors.py`. This serves just to demonstrate the changes and is by no means a comprehensive test ready for production.

## Related Issues
Resolves #153 

## Additional Comments
**Please keep in mind that this is meant to serve as a draft PR and is by no means production-ready.** The changes made to the code base are very crude and the aim was only to show how it may be possible to incorporate `safetensors` support in `hezar`. After the architectural details and design decisions regarding how and where this change should be introduced within the codebase are approved, I can happily edit this PR (or submit a new one) with a cleaner code that adheres to this library's standards.

## Notes
- `Model.push_to_hub()` also requires changes but for the purposes of this quick prototype it was left unchanged for the time being.

### CODE REVIEW

**Comment by arxyzan** [comment]
Great job @Adversarian, this is so cool! I just took a quick look at it and it seems pretty solid. I'll try to test it out very soon in a day or two and let you know.

**Comment by arxyzan** [comment]
@Adversarian Can you please rename or re-apply your changes in another branch instead of `main` ? (To avoid conflicts and easier checkout in dev tools)

**Comment by Adversarian** [comment]
@arxyzan Of course, it's no problem. Should I close this PR and re-open another one from the new branch? Because I'm not sure how to edit this one so that the changes are pulled from the new branch.

**Comment by arxyzan** [comment]
@Adversarian Actually the correct way to do it is to create a branch from the main branch of your fork and create a PR to merge that branch to the main branch of Hezar.

**Comment by Adversarian** [comment]
@arxyzan I know, that's what I meant by what I said. The reason I didn't do that was because I was just prototyping so I didn't really bother with git etiquette. I'm going to close this and re-open another PR from a new branch after syncing with `hezar` (since it's 1 commit ahead of mine since yesterday).

**Comment by Adversarian** [comment]
@arxyzan Reopened this at PR #157 with a different branch name. Let's continue the discussion from there.

**Pull request closed without merging**
