### PR TITLE
Add annotation to Model.load to return Model in model.py

### PR DESCRIPTION
**Pull request by pooya-mohammadi**
This is critical, in the code after loading `Model`, there is no intelligence whatsoever!
I tested it with python 3.8 and it works
image

### CODE REVIEW

**Comment by pooya-mohammadi** [comment]
I removed the "Pooya" but it still worked too. I think pycharm is helping more than enough!
At least, it has no errors in python 3.8 and it's safe to use

**Comment by arxyzan** [comment]
Cool! Can you apply this change to other main modules?
- Embedding
- Dataset
- Tokenizer
- TextNormalizer
- Metric
- Config

@pooya-mohammadi

**Comment by pooya-mohammadi** [comment]
@arxyzan jan, I think Mertic has no `load` method

**Review by arxyzan — APPROVED** [review]

**Comment by arxyzan** [comment]
@pooya-mohammadi  You're right. Metrics don't have load themselves. A metric is constructed by a config file which can be loaded from hub or from local disk.

**Pull request merged**
